<a href="https://colab.research.google.com/github/Ron0524/note/blob/master/20200326.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
ar2=np.array([[0,3,5],[2,8,7]])
ar2.shape

(2, 3)

In [3]:
import numpy as np
ar2=np.array([[0,3,5],[2,8,7]])
ar2.ndim

2

In [4]:
import numpy as np
ar= np.array([2,4,6,8])
ar.dtype

dtype('int64')

In [6]:
import numpy as np
ar= np.array([2,-1,6,3],dtype = 'float')
ar

array([ 2., -1.,  6.,  3.])

In [7]:
ar.dtype

dtype('float64')

In [8]:
ar = np.array([2.,4,6,8]);
ar.dtype

dtype('float64')

In [9]:
f_ar = np.array([13,-3,8.88])
f_ar

array([13.  , -3.  ,  8.88])

In [10]:
intf_ar=f_ar.astype(int)
intf_ar

array([13, -3,  8])

In [12]:
ar9 = np.eye(3)
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
ar10 = np.diag((2,1,4,6))
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [14]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [15]:
a=np.array([0,1,2])
np.tile(a,2)

array([0, 1, 2, 0, 1, 2])

In [16]:
np.tile(a,(2,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [17]:
np.tile(a,(2,1,2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])