<a href="https://colab.research.google.com/github/Ron0524/note/blob/master/Data_Analyze.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**
## np.random.randn

隨機產生亂數

In [1]:
import numpy as np

data = np.random.randn(2,3)
data

array([[ 1.19988991, -0.54845366, -1.16429113],
       [-0.42360933,  0.74809858,  0.49807955]])

In [2]:
data *10

array([[ 11.99889906,  -5.48453662, -11.64291126],
       [ -4.23609325,   7.48098581,   4.9807955 ]])

In [3]:
data + data

array([[ 2.39977981, -1.09690732, -2.32858225],
       [-0.84721865,  1.49619716,  0.9961591 ]])

# **pandas**

### DataFrame
將陣列以Table的方式呈現

In [6]:
import pandas as pd
from pandas import DataFrame

data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2